"""Initial migration

Revision ID: 418a9ef201e4
Revises: 
Create Date: 2026-05-11 19:26:02.559503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418a9ef201e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'SECRETARIO', 'CONSULTOR', name='user_roles'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'DEFERIDO', 'INDEFERIDO', name='event_status'), nullable=True),
    sa.Column('oficio_path', sa.String(length=255), nullable=True),
    sa.Column('justificativa_indeferimento', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_decisao', sa.DateTime(), nullable=True),
    sa.Column('responsavel_decisao_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_decisao_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(length=255), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexos')
    op.drop_table('eventos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
